# Generated by Django 2.1.3 on 2018-11-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_auto_20181110_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_small', models.CharField(max_length=500)),
                ('img_medium', models.CharField(max_length=500)),
                ('img_large', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
