# Generated by Django 2.1.3 on 2018-11-18 07:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_units', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.Recipe')),
            ],
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='in_grams',
            new_name='weight_in_grams',
        ),
        migrations.AlterField(
            model_name='image_container',
            name='img_large',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image_container',
            name='img_medium',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.Image_container'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='cakes.Usage', to='cakes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='cakes.Tag'),
        ),
    ]
