# Generated by Django 2.1.3 on 2018-11-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_auto_20181118_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price_per_unit',
            new_name='price_per_gram',
        ),
    ]
